version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: server.py
    volumes:
      - ./:/app

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5001:5000"
